name: Build and Deploy Android

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "adopt"
          cache: 'gradle'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-Validation-action@v1

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Ensure Assets Directory Exists
        run: mkdir -p android/app/src/main/assets

      - name: Bundle the app
        run: |
          npx react-native bundle \
          --platform android \
          --dev false \
          --entry-file index.js \
          --bundle-output android/app/src/main/assets/index.android.bundle \
          --assets-dest android/app/src/main/res

      - name: Set Gradlew Permissions
        run: chmod +x android/gradlew

      - name: Run Tests
        run: npm test

      - name: Build application
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Check if APK exists
        run: |
          if [ -f android/app/build/outputs/apk/release/app-release.apk ]; then
            echo "APK exists!"
          else
            echo "APK does not exist!"
            exit 1
          fi

      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: Build
      #     path: android/app/build/outputs/apk/release/app-release.apk

      # - name: Upload artifact to Firebase App Distribution
      #   id: testing_outputs
      #   uses: wzieba/Firebase-Distribution-Github-Action@v1
      #   with:
      #     appId: ${{secrets.FIREBASE_APP_ID}}
      #     serviceCredentialsFileContent: ${{secrets.CREDENTIAL_FILE_CONTENT}}
      #     groups: testers
      #     file: android/app/build/outputs/apk/release/app-release.apk

      # - name: Print Firebase Distribution Links
      #   run: |
      #     echo "Firebase Console URI: ${{steps.testing_outputs.outputs.FIREBASE_CONSOLE_URI}}"
      #     echo "Testing URI: ${{steps.testing_outputs.outputs.TESTING_URI}}"
      #     echo "Binary Download URI: ${{steps.testing_outputs.outputs.BINARY_DOWNLOAD_URI}}"

      # Optional: Enable this only if you have working SMTP setup
      # - name: Send Email Notification
      #   uses: dawidd6/action-send-mail@v3
      #   with:
      #     server_address: smtp.gmail.com
      #     server_port: 587
      #     username: mynulislamridoy
      #     password: ${{secrets.SMTP_PASSWORD}}
      #     subject: "A New Build Released, Check It Out"
      #     to: mynul.ir@tudotechnologies.com
      #     from: homeexercise8@gmail.com
      #     body: |
      #       Dear Sir/Madam,

      #       These links provide direct access to the updated version of the app. Use any of these links to download and test the app.

      #       - Firebase Console URI: ${{steps.testing_outputs.outputs.FIREBASE_CONSOLE_URI}}
      #       - App URI: ${{steps.testing_outputs.outputs.TESTING_URI}}
      #       - Binary Download URI: ${{steps.testing_outputs.outputs.BINARY_DOWNLOAD_URI}}

      #       We encourage you to explore these new features and functionalities and let us know what you think.
