name: react-native-android-build-apk
on:
  push:
    branches:
      - main
# env:
  # APP_CENTER_TOKEN: ${{ secrets.APP_CENTER_ANDROID_RELEASE_KEY}}
  # APP_NAME: 'vnaik-isc/iSchoolConnect-Student-Android'
  # TESTING_GROUP: 'Release_Build_Testers'
  # UPLOAD_FILE: 'android/app/build/outputs/apk/dev/release/app-dev-release.apk'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-Validation-action@v1

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '22.12.0'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build android
        run: cd android && ./gradlew assembleDevRelease

      # - name: Upload to App Center
      #   uses: wzieba/AppCenter-Github-Action@v1
      #   with:
      #     appName: ${{ env.APP_NAME }}
      #     token: ${{ env.APP_CENTER_TOKEN }}
      #     group: ${{ env.TESTING_GROUP }}
      #     file: ${{ env.UPLOAD_FILE }}
      #     notifyTesters: true
      #     debug: true
